import React, { useState } from "react";
import axios from "axios";
import { toast } from "react-toastify";
import { UploadCloud, Image as ImageIcon, CheckCircle } from "lucide-react";
import { useEffect } from "react";



const API = "https://quickinvoice-backend-1.onrender.com"


const AddProduct = () => {
  const token = localStorage.getItem("token");
  const [name, setName] = useState("");
  const [price, setPrice] = useState("");
  const [category, setCategory] = useState("");
  const [description, setDescription] = useState("");
  // const [loadingDescription, setLoadingDescription] = useState(false);
  const [image, setImage] = useState(null);
  const [preview, setPreview] = useState(null);
  const [loading, setLoading] = useState(false);
  const [success, setSuccess] = useState(false);

  const categories = ["Electronics",'Gadgets', "Fashion", "Home","Hot Food", "Books", "Toys", "Health", "Sports","Groceries", "Beauty", "Automotive","Other"]



  //shipping categories
  const [shippingCategories, setShippingCategories] = useState([]);
  const [shippingCategory, setShippingCategory] = useState("");
  const [shippingCategoryId, setShippingCategoryId] = useState(null);
  const fetchShippingCategories = async () => {
    try {
      const res = await axios.get(`${API}/api/logistics/categories`);
      if (res.data.status === "success") {
        setShippingCategories(res.data.data);
      }
    } catch (err) {
      console.error("Error fetching shipping categories:", err);
    }
  };


  useEffect(()=>{
    fetchShippingCategories()
  },[])

  

  const handleImageChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      setImage(file);
      setPreview(URL.createObjectURL(file));
    }
  };
  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!name.trim() || !price.trim()) {
      toast.error("Please fill in all required fields.");
      return;
    }
    const formData = new FormData();
    formData.append("name", name);
    formData.append("price", price);
    formData.append("category", category);
    formData.append("description", description);

    formData.append("shipping_category", shippingCategory)
    formData.append("shipping_category_id", shippingCategoryId);
    if (image) formData.append("image", image);
    try {
      setLoading(true);
      const res = await axios.post(`${API}/api/marketsquare/product`, formData, {
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "multipart/form-data",
        },
      });
      console.log(res);
      
      toast.success("Product added successfully!");
      setSuccess(true);
      setName("");
      setPrice("");
      setDescription("");
      setImage(null);
      setPreview(null);
    } catch (err) {
      console.error(err);
      toast.error("Failed to add product. Please try again.");
    } finally {
      setLoading(false);
    }
  };

// const generateWithQuickBuddy = async () => {
    
//         if (!name.trim()) {
//           toast.error("Please enter a product name first.");
//           return;
//         }
//         try {
//           setLoadingDescription(true);
//           const res = await axios.post(
//             `${API}/api/quickbuddy/generate-description`,
//             { name: name }, 
//             {
//               headers: { Authorization: `Bearer ${token}` },
//             }
//           );
//           setDescription(res.data.description);
//           toast.success("Description generated by Quick Buddy!");
//         } catch (err) {
//           console.error(err);
//           toast.error("Failed to generate description. Try again.");
//         } finally {
//           setLoadingDescription(false);
//         }
// };

  return (
    <div className="min-h-screen bg-gradient-to-br from-[#0046A5] to-[#00B86B] flex items-center justify-center px-4 py-10">
      <div className="bg-white shadow-xl rounded-2xl p-8 w-full max-w-md animate-fadeIn">
        {success ? (
          <div className="text-center">
            <CheckCircle className="text-green-600 mx-auto mb-4" size={50} />
            <h2 className="text-2xl font-bold text-[#0046A5] mb-2">
              Product Added!
            </h2>
            <p className="text-gray-600 mb-6">
              Your product has been listed successfully on MarketZone.
            </p>
            <div className="flex flex-col items-center space-y-3 mt-6">
                <button
                    onClick={() => setSuccess(false)}
                    className="w-full max-w-xs bg-[#0046A5] text-white px-6 py-2 rounded-lg hover:bg-[#00398D] transition"
                >
                    Add Another Product
                </button>
                <button
                    onClick={() => (window.location.href = '/product')}
                    className="w-full max-w-xs bg-gradient-to-br from-[#0046A5] to-[#00B86B] text-white px-6 py-2 rounded-lg hover:opacity-90 transition"
                >
                    Go to Product List
                </button>
                </div>
          </div>
        ) : (
          <>
            <h1 className="text-2xl font-bold text-[#0046A5] mb-3 text-center">
              Add New Product 🛍️
            </h1>
            <p className="text-gray-600 text-center mb-6">
              Upload your product details below.
            </p>
            <form onSubmit={handleSubmit} className="space-y-5">
              {/* Name */}
              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-1">
                  Product Name <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  placeholder="Enter product name"
                  className="w-full border rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-[#0046A5]"
                />
              </div>
              {/* Price */}
              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-1">
                  Price (₦) <span className="text-red-500">*</span>
                </label>
                <input
                  type="number"
                  value={price}
                  onChange={(e) => setPrice(e.target.value)}
                  placeholder="Enter price"
                  className="w-full border rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-[#0046A5]"
                />
              </div>
              {/* Category */}
              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-1">
                  Category <span className="text-red-500">*</span>
                </label>
                <select
                  value={category}
                  onChange={(e) => setCategory(e.target.value)}
                  className="w-full border rounded-lg px-3 py-2 bg-white focus:outline-none focus:ring-2 focus:ring-[#0046A5]"
                >
                  <option value="">Select a category</option>
                  {categories.map((cat, index) => (
                    <option key={index} value={cat}>
                      {cat}
                    </option>
                  ))}
                </select>
              </div>

                  {/* Shipping Category */}
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-1">
                Shipping Category <span className="text-red-500">*</span>
              </label>
              <select
                value={shippingCategory}
                onChange={(e) => {
                  const selected = shippingCategories.find(
                    (c) => c.category === e.target.value
                  );
                  setShippingCategory(e.target.value);
                  setShippingCategoryId(selected?.category_id);
                }}
                className="w-full border rounded-lg px-3 py-2 bg-white focus:outline-none focus:ring-2 focus:ring-[#0046A5]"
              >
                <option value="">Select a shipping category</option>
                {shippingCategories.map((cat) => (
                  <option key={cat.category_id} value={cat.category}>
                    {cat.category}
                  </option>
                ))}
              </select>
            </div>

              {/* Description */}
              {/* <div> */}
                <label className="block text-sm font-semibold text-gray-700 mb-1">
                    Description
                </label>
                <div className="flex items-start space-x-2">
                    <textarea
                    value={description}
                    onChange={(e) => setDescription(e.target.value)}
                    placeholder="Please put a detailed description of the product."
                    rows="3"
                    className="w-full border rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-[#0046A5]"
                    ></textarea>
                    
                  </div> 
                
              {/* Image Upload */}
              <div className="border-2 border-dashed rounded-lg p-4 flex flex-col items-center justify-center hover:bg-gray-50 transition">
                {preview ? (
                  <img
                    src={preview}
                    alt="Preview"
                    className="w-32 h-32 object-cover rounded-lg mb-2"
                  />
                ) : (
                  <ImageIcon size={40} className="text-gray-400 mb-2" />
                )}
                <label
                  htmlFor="imageUpload"
                  className="cursor-pointer text-[#0046A5] font-semibold hover:underline"
                >
                  {preview ? "Change Image" : "Upload Image"}
                </label>
                <input
                  id="imageUpload"
                  type="file"
                  accept="image/*"
                  onChange={handleImageChange}
                  className="hidden"
                />
              </div>
              <small className="text-gray-500 block mt-1">Make sure image size is not more than 5MB</small>
              {/* Submit */}
              <button
                type="submit"
                disabled={loading}
                className="w-full bg-[#0046A5] text-white py-2 rounded-lg hover:bg-[#00398D] transition disabled:opacity-60 flex items-center justify-center"
              >
                {loading ? (
                  <>
                    <UploadCloud size={18} className="mr-2 animate-pulse" /> Uploading...
                  </>
                ) : (
                  <>
                    <UploadCloud size={18} className="mr-2" /> Add Product
                  </>
                )}
              </button>
            </form>
          </>
        )}
      </div>
    </div>
  );
};
export default AddProduct;








